import type { Metadata } from "next";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Apso privacy policy. How we collect, use, and protect your information.",
};

export default function PrivacyPolicyPage() {
  return (
    <Section>
      <Container className="max-w-[860px]">
        <h1 className="text-h1 text-fg-1 mb-8">Privacy Policy</h1>
        <div className="prose max-w-none text-fg-3 space-y-6">
          <p className="text-sm text-fg-4">Last updated: June 2026</p>

          <p>
            Mavric Technology, LLC (&quot;Mavric,&quot; &quot;we,&quot; &quot;us&quot;) operates the Apso platform
            (apso.ai, app.apso.cloud, and related services). This policy describes how we
            collect, use, and protect your information when you use our services.
          </p>

          <h2 className="text-h3 text-fg-1">Information We Collect</h2>
          <p>
            We collect information you provide directly: name, email address, company name
            when you create an account or contact us. We collect usage data through PostHog
            analytics, including pages visited, features used, and interaction patterns. We
            collect technical data such as browser type, IP address, and device information.
          </p>

          <h2 className="text-h3 text-fg-1">How We Use Your Information</h2>
          <p>
            We use your information to provide and maintain the Apso platform, process
            transactions and send billing notifications, communicate about service updates
            and support requests, analyze usage patterns to improve the product, and comply
            with legal obligations.
          </p>

          <h2 className="text-h3 text-fg-1">Data Sharing</h2>
          <p>
            We do not sell your personal information. We share data with service providers
            who assist in operating our platform (AWS for hosting, Stripe for payments,
            Resend for email, PostHog for analytics). These providers are bound by their
            own privacy policies and data processing agreements.
          </p>

          <h2 className="text-h3 text-fg-1">Your Code and Data</h2>
          <p>
            Code generated by Apso belongs to you. Your application data stored in deployed
            services is hosted on AWS infrastructure under your control. We do not access,
            analyze, or share your application data or generated code.
          </p>

          <h2 className="text-h3 text-fg-1">Security</h2>
          <p>
            We use industry-standard security practices including encryption in transit
            (TLS), encryption at rest (AES-256 for databases), and secure credential storage
            (AWS Secrets Manager). We conduct regular security reviews of our infrastructure.
          </p>

          <h2 className="text-h3 text-fg-1">Your Rights</h2>
          <p>
            You can request access to, correction of, or deletion of your personal data by
            contacting us at privacy@mavric.tech. You can close your account at any time.
            Account deletion removes your personal data from our systems, though we may
            retain certain records as required by law.
          </p>

          <h2 className="text-h3 text-fg-1">Changes</h2>
          <p>
            We may update this policy from time to time. We will notify you of material
            changes by posting the updated policy on this page and updating the &quot;Last
            updated&quot; date.
          </p>

          <h2 className="text-h3 text-fg-1">Contact</h2>
          <p>
            For questions about this privacy policy, contact us at privacy@mavric.tech or
            through our <a href="/contact" className="text-brand hover:text-brand-hover">contact form</a>.
          </p>
        </div>
      </Container>
    </Section>
  );
}
